test

diff --git a/.github/workflows/Software_Download.yml b/.github/workflows/Software_Download.yml
--- a/.github/workflows/Software_Download.yml
+++ b/.github/workflows/Software_Download.yml
@@ -6,16 +6,63 @@ jobs:
   build:
     name: Software Download link
     runs-on: ubuntu-latest
+    env:
+      OUTPUT_FILE: "bg.md"
     steps:
         - uses: actions/checkout@v4
         - name: Set up Python
           uses: actions/setup-python@v5
           with:
             python-version: "3.x"
+        - name: massage
+          run: |
+             # 创建文件
+              touch "${OUTPUT_FILE}"
+              # 检查文件是否创建成功
+              if [ $? -ne 0 ]; then
+                echo "Failed to create file"
+                exit 1
+              fi
+
+              # 生成 Markdown 内容
+              cat <<EOF > "${OUTPUT_FILE}"
+              *bold \*text*  
+              _italic \*text_  
+              __underline__  
+              ~strikethrough~  
+              ||spoiler||  
+              *bold _italic bold ~italic bold strikethrough ||italic bold strikethrough spoiler||~ __underline italic bold___ bold*  
+              [inline URL](http://www.example.com/)  
+              [inline mention of a user](tg://user?id=123456789)  
+              ![👍](tg://emoji?id=5368324170671202286)  
+              \`inline fixed-width code\`  
+              \`\`\`  
+              pre-formatted fixed-width code block  
+              \`\`\`  
+              \`\`\`python  
+              pre-formatted fixed-width code block written in the Python programming language  
+              \`\`\`  
+              > Block quotation started  
+              > Block quotation continued  
+              > Block quotation continued  
+              > Block quotation continued  
+              > The last line of the block quotation  
+              **> The expandable block quotation started right after the previous block quotation  
+              > It is separated from the previous block quotation by an empty bold entity  
+              > Expandable block quotation continued  
+              > Hidden by default part of the expandable block quotation started  
+              > Expandable block quotation continued  
+              > The last line of the expandable block quotation with the expandability mark||\  
+              EOF
+
+              # 检查文件是否正确生成
+              if [ ! -f "${OUTPUT_FILE}" ]; then
+                echo "Failed to write content to file"
+                exit 1
+              fi
         - name: 'Send telegram message'
           uses: appleboy/telegram-action@master
           with:
             to: ${{ secrets.TELEGRAM_ID }}
             token: ${{ secrets.TELEGRAM_TOKEN }}
-            message: |
-                this is the test message
+            format: ./bg.md
